version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'reserva-espacios-webserver'
    restart: 'always'
    links: 
      - mysql
  mysql:
    image: mysql:5.7
    container_name: 'reserva-espacios-mysql'
    restart: 'always'
    volumes: 
      - dbdata:/var/lib/mysql                                                                                                                                                                             
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: bookedscheduler
      MYSQL_ROOT_PASSWORD: 123secret
      MYSQL_USER: bookedscheduler
      MYSQL_PASSWORD: 123secret

volumes:
  dbdata:
  dblogs:
