version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: '7.1.x-webserver'
    restart: 'always'
    ports:
      - "81:81"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/reservaespacios/html/booked
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: '5.7-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/www/reservaespacios/html/booked
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/www/reservaespacios/html/booked
    environment:
      MYSQL_DATABASE: bookedscheduler
      MYSQL_ROOT_PASSWORD: 123secret
      MYSQL_USER: bookedscheduler
      MYSQL_PASSWORD: 123secret