version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    ports:
      - "4100:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/reservaespacios/html/booked
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2

  mysql:
    build: ./bin/mysql
    ports:
      - "3307:3306"

