version: "3"

services:
  webserver:
    build: 
      context: .
      dockerfile: ./bin/webserver/Dockerfile
    ports:
      - "6001:80"
    links: 
      - mysql
    env_file:
      - reserva-espacios.env
#    volumes: 
#      - ${DOCUMENT_ROOT-./www}:/var/www/reservaespacios/html/booked
#      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
#      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
#      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
